Sampler : 
  sampler_type : HMC
  mass : [1.,1.]
  t : 0.12
  dt : 
    - .01
    - .02
    - .03
    - .04
    - .06
    - .12

General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 10
  burn_in : 100
  n_chains : 20
  n_samples : 3000
  fig_name : dt_scan
  save_fig : True
  param_to_scan : dt
