Case1 : 
  sampler_type : RWMC
  title : RWMC
  step_size : [.075,.075]
  n_samples : 70100

Case2 : 
  sampler_type : HMC
  title : HMC
  mass : [.85,.85]
  t : 0.09
  dt : 0.03
  n_samples : 10100

General :
  seed : 1234
  initial_condition : [0.,0.]
  burn_in : 100
  n_chains : 5
