Case1 : 
  sampler_type : HMC
  title : Asymmetric mass
  mass : [1.5,.5]
  t : 0.5
  dt : 0.1

Case2 : 
  sampler_type : HMC
  title : Symmetric mass
  mass : [1.,1.]
  t : 0.5
  dt : 0.1

General :
  seed : 1234
  initial_condition : [0.,0.]
  burn_in : 100
  n_chains : 3
  n_samples : 1000
  fig_name : mass_sym
