Case1 : 
  sampler_type : HMC
  title : Asymmetric mass
  mass : [1.5,.5]
  t : .21
  dt : 0.03

Case2 : 
  sampler_type : HMC
  title : Symmetric mass
  mass : [.75,.75]
  t : .21
  dt : 0.03

General :
  seed : 1234
  initial_condition : [.5,0.]
  burn_in : 100
  n_chains : 3
  alpha : 1000
  n_samples : 3000
  fig_name : mass_sym
