Sampler : 
  sampler_type : HMC
  t : .21 #.21
  dt : .01 # 0.03
  mass : [0.15, 0.3, 0.5, 0.7, 0.85, .95, 1.05, 1.15, 1.3, 1.6, 2.]
General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 1000
  burn_in : 100
  n_chains : 15
  n_samples : 3000
  fig_name : mass_scan
  save_fig : True
  param_to_scan : mass
