Case1 : 
  sampler_type : HMC
  title : Big mass
  mass : [2.,2.]
  t : 1.
  dt : 0.03

Case2 : 
  sampler_type : HMC
  title : Right mass
  mass : [.05,.05]
  t : 1.
  dt : 0.05

General :
  seed : 1234
  initial_condition : [0.,0.]
  burn_in : 100
  n_chains : 3
  n_samples : 1000
  fig_name : mass_scale
