Sampler : 
  sampler_type : HMC
  t : .15 #.21
  dt : .01 # 0.03
  mass : 
    - [0.1,0.1]
    - [0.2,0.2]
    - [0.3,0.3]
#    - [0.4,0.4]
    - [0.5, 0.5]
    - [0.675,0.675]
    - [0.85,0.85]
    - [1.,1.]
    - [1.15,1.15]
    - [1.3,1.3]
    - [1.5,1.5]
    - [1.9,1.9]
    - [2.2,2.2]

General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 10
  burn_in : 100
  n_chains : 10
  n_samples : 3000
  fig_name : mass_scan
  save_fig : True
  param_to_scan : mass
