Case1 : 
  sampler_type : HMC
  title : Asymmetric mass
  mass : [5.,.85]
  t : .21
  dt : 0.01

Case2 : 
  sampler_type : HMC
  title : Symmetric mass
  mass : [.85,.85]
  t : .21
  dt : 0.01

General :
  seed : 1234
  initial_condition : [.5,0.]
  burn_in : 100
  n_chains : 10
  alpha : 1000
  n_samples : 3000
  fig_name : mass_sym
