HMC : 
  sampler_type : HMC
  mass : 1.
  t : .09
  dt : .03

RWMC : 
  sampler_type : RWMC
  step_size : [0.085,0.085]

General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 1000
  burn_in : 100
  n_chains : 5
  n_samples :
  - 250
  - 500
  - 1000
  - 2500
  - 5000
  - 7500
  - 10000
  fig_name : nsamples_evolution
  save_fig : True
