Case1 : 
  sampler_type : RWMC
  title : RWMC
  step_size : [1.,1.]

Case2 : 
  sampler_type : HMC
  title : HMC
  mass : [1.,1.]
  t : 0.5
  dt : 0.1

General :
  seed : 1234
  initial_condition : [0.,0.]
  alpha : 10
  burn_in : 100
  n_chains : 1
  n_samples : 1000
  fig_name : rwmc_vs_hmc
