Case1 : 
  sampler_type : RWMC
  title : RWMC
  step_size : [1.,1.]

Case2 : 
  sampler_type : HMC
  title : HMC
  mass : [.5,.5]
  t : 0.15
  dt : 0.03

General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 1000
  burn_in : 100
  n_chains : 1
  n_samples : 1000
  fig_name : rwmc_vs_hmc
