Sampler : 
  sampler_type : HMC
  mass : 1.
  dt : 0.01
  t : 
    - .03
    - .04
    - .055
    - .07
    - .09
    - .12
    - .15

General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 1000
  burn_in : 100
  n_chains : 10
  n_samples : 3000
  fig_name : t_scan
  save_fig : True
  param_to_scan : t
