Sampler : 
  sampler_type : HMC
  mass : [1.,1.]
  dt : 0.01
  t : 
    - .02
    - .04
    - .06
    - .08
    - .12
    - .16

General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 10
  burn_in : 100
  n_chains : 5
  n_samples : 3000
  fig_name : t_scan
  save_fig : True
  param_to_scan : t
