Sampler : 
  sampler_type : HMC
  mass : [.5,.5]
  dt : 0.03
  t : 
    - .12
    - .15
    - .21
    - .27
    - .33

General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 1000
  burn_in : 100
  n_chains : 5
  n_samples : 3000
  fig_name : t_scan
  save_fig : True
  param_to_scan : t
