Sampler : 
  sampler_type : HMC
#  mass : .85
  mass : 3.4
#  mass : .2125
  dt : 0.01
  t : 
    - .02
    - .04
    - .06
    - .08
  #  - .10
    - .12
  #  - .14
    - .17
  #  - .21
    - .25

General :
  seed : 1234
  initial_condition : [0.5,0.]
  alpha : 1000
  burn_in : 100
  n_chains : 10
  n_samples : 3000
  fig_name : t_scan
  save_fig : True
  param_to_scan : t
